import React, { Component } from 'react';
import { Field, reduxForm } from 'redux-form';

class PostsNew extends Component{
    // field contains event handlers that need to be wired up to the JSX so that <Field is wired up
    // to the <input
    renderField(field){
        // field.input contains event handlers like onChange, onBlur, value of input etc
        return (
            <div className="form-group">
                <label>{field.label}</label>
                <input type="text" className="form-control"
                    /* field.input instead of this
                        onChange={field.input.onChange}
                        onFocus={field.input.onFocus}
                        onBlur={field.input.onBlur}
                        */
                    {...field.input} />
            </div>
        );
    }

    render(){
        return(
            <form>
                <Field
                    label="Title"
                // name property specifies what piece of state this field produces
                    name="title"
                    // component property takes in a function that will be used to display this field
                    component={this.renderField}
                />
                <Field
                    label="Tags"
                    name="tags"
                    // no () required since we are passing a reference to a function
                    component={this.renderField}
                />
                <Field
                    label="Post Content"
                    name="content"
                    component={this.renderField}
                />
            </form>
        );
    }
}

// Helper to allow redux form to communicate from the component to the reducer that was set up
export default reduxForm({
    // Name of the form; In case of multiple forms on the page
    form: 'PostsNewForm' // Specifies namespace for the state generated by this component
})(PostsNew);